# Funding sources for the OSINT Sentinel Workstation
# GitHub Sponsors, Discord, and commercial license sales

github: # Add your GitHub username here when ready
custom: ["https://discord.gg/visentrix"]
